[workspace]
members = ["bevy_mod_n2dmap", "n2dmap", "n2dmap_cli"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.11-dev", default-features = false }
image = { version = "0.24.6", default-features = false }
fft2d = "0.1.0"
